## P8

In [4]:
import pandas as pd
import numpy as np
csv = pd.read_csv('./Parking.csv')
print(csv.info())
print(csv.shape)
print(csv.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Summons Number      128 non-null    int64
 1   Plate ID            128 non-null    object
 2   Registration State  128 non-null    object
 3   Plate Type          128 non-null    object
 4   Issue Date          128 non-null    object
 5   Violation Code      128 non-null    int64
 6   Vehicle Body Type   128 non-null    object
 7   Vehicle Make        128 non-null    object
 8   Issuing Agency      128 non-null    object
 9   Street Code1        98 non-null     float64
dtypes: float64(1), int64(2), object(7)
memory usage: 10.1+ KB
None
(128, 10)
       Summons Number  Violation Code  Street Code1
count    1.280000e+02      128.000000     98.000000
mean     6.806207e+09       34.328125   2450.979592
std      2.362242e+09       18.551104   2427.015120
min      1.400876e+09        5.000000     19.000000
25%      5.092465e+09       20.000000    630.500000
50%      8.124282e+09       36.000000   1777.000000
75%      8.482552e+09       46.000000   3450.500000
max      8.581154e+09       78.000000  16135.000000

In [18]:
df_deleted = csv.dropna()
print("DataFrame after deleting rows with missing data:")
print(df_deleted)

df_replaced = csv.fillna(value='replacement_value')
print("DataFrame after replacing missing data:")
print(df_replaced)

df_ffill = csv.ffill()
print("DataFrame after forward filling missing data:")
print(df_ffill)

df_bfill = csv.bfill()
print("DataFrame after backward filling missing data:")
print(df_bfill)

DataFrame after deleting rows with missing data:
     Summons Number Plate ID Registration State Plate Type  Issue Date
3        8478629828  66623ME                 NY        COM   6/14/2017  \
4        7868300310  37033JV                 NY        COM  11/21/2016
6        1413609545   X20DCM                 NJ        PAS    8/3/2016
11       8009901763  13657MD                 NY        COM   9/27/2016
13       1416492320  FGR5997                 NY        PAS   9/30/2016
..              ...      ...                ...        ...         ...
123      8377006390  GCR2084                 NY        PAS   7/19/2016
124      8482178982  76691MH                 NY        COM   4/24/2017
125      1417599716  12203MG                 NY        COM   12/1/2016
126      7813974049  GLS7002                 NY        PAS    9/9/2016
127      8149510126  GTP8988                 NY        PAS   8/10/2016

     Violation Code Vehicle Body Type Vehicle Make Issuing Agency
3                47              REFG        MITSU              T  \
4                69              DELV        INTER              T
6                40               SDN        TOYOT              P
11               19              DELV        KENWO              T
13               21               SDN        NISSA              P
..              ...               ...          ...            ...
123              48              4DSD        HONDA              T
124              47               VAN        FRUEH              T
125              46               VAN        FRUEH              P
126              40              SUBN         FORD              T
127              16              2DSD        SMART              T

     Street Code1
3           161.0
4           151.0
6           547.0
11          151.0
13         5362.0
..            ...
123        5952.0
124         181.0
125        2569.0
126        2969.0
127        4133.0

[98 rows x 10 columns]
DataFrame after replacing missing data:
     Summons Number Plate ID Registration State Plate Type  Issue Date
0        5092469481  GZH7067                 NY        PAS   7/10/2016  \
1        5092451658  GZH7067                 NY        PAS    7/8/2016
2        4006265037  FZX9232                 NY        PAS   8/23/2016
3        8478629828  66623ME                 NY        COM   6/14/2017
4        7868300310  37033JV                 NY        COM  11/21/2016
..              ...      ...                ...        ...         ...
123      8377006390  GCR2084                 NY        PAS   7/19/2016
124      8482178982  76691MH                 NY        COM   4/24/2017
125      1417599716  12203MG                 NY        COM   12/1/2016
126      7813974049  GLS7002                 NY        PAS    9/9/2016
127      8149510126  GTP8988                 NY        PAS   8/10/2016

     Violation Code Vehicle Body Type Vehicle Make Issuing Agency
0                 7              SUBN        TOYOT              V  \
1                 7              SUBN        TOYOT              V
2                 5              SUBN         FORD              V
3                47              REFG        MITSU              T
4                69              DELV        INTER              T
..              ...               ...          ...            ...
123              48              4DSD        HONDA              T
124              47               VAN        FRUEH              T
125              46               VAN        FRUEH              P
126              40              SUBN         FORD              T
127              16              2DSD        SMART              T

          Street Code1
0    replacement_value
1    replacement_value
2    replacement_value
3                161.0
4                151.0
..                 ...
123             5952.0
124              181.0
125             2569.0
126             2969.0
127             4133.0

[128 rows x 10 columns]
DataFrame after forward filling missing data:
     Summons Number Plate ID Registration State Plate Type  Issue Date
0        5092469481  GZH7067                 NY        PAS   7/10/2016  \
1        5092451658  GZH7067                 NY        PAS    7/8/2016
2        4006265037  FZX9232                 NY        PAS   8/23/2016
3        8478629828  66623ME                 NY        COM   6/14/2017
4        7868300310  37033JV                 NY        COM  11/21/2016
..              ...      ...                ...        ...         ...
123      8377006390  GCR2084                 NY        PAS   7/19/2016
124      8482178982  76691MH                 NY        COM   4/24/2017
125      1417599716  12203MG                 NY        COM   12/1/2016
126      7813974049  GLS7002                 NY        PAS    9/9/2016
127      8149510126  GTP8988                 NY        PAS   8/10/2016

     Violation Code Vehicle Body Type Vehicle Make Issuing Agency
0                 7              SUBN        TOYOT              V  \
1                 7              SUBN        TOYOT              V
2                 5              SUBN         FORD              V
3                47              REFG        MITSU              T
4                69              DELV        INTER              T
..              ...               ...          ...            ...
123              48              4DSD        HONDA              T
124              47               VAN        FRUEH              T
125              46               VAN        FRUEH              P
126              40              SUBN         FORD              T
127              16              2DSD        SMART              T

     Street Code1
0             NaN
1             NaN
2             NaN
3           161.0
4           151.0
..            ...
123        5952.0
124         181.0
125        2569.0
126        2969.0
127        4133.0

[128 rows x 10 columns]
DataFrame after backward filling missing data:
     Summons Number Plate ID Registration State Plate Type  Issue Date
0        5092469481  GZH7067                 NY        PAS   7/10/2016  \
1        5092451658  GZH7067                 NY        PAS    7/8/2016
2        4006265037  FZX9232                 NY        PAS   8/23/2016
3        8478629828  66623ME                 NY        COM   6/14/2017
4        7868300310  37033JV                 NY        COM  11/21/2016
..              ...      ...                ...        ...         ...
123      8377006390  GCR2084                 NY        PAS   7/19/2016
124      8482178982  76691MH                 NY        COM   4/24/2017
125      1417599716  12203MG                 NY        COM   12/1/2016
126      7813974049  GLS7002                 NY        PAS    9/9/2016
127      8149510126  GTP8988                 NY        PAS   8/10/2016

     Violation Code Vehicle Body Type Vehicle Make Issuing Agency
0                 7              SUBN        TOYOT              V  \
1                 7              SUBN        TOYOT              V
2                 5              SUBN         FORD              V
3                47              REFG        MITSU              T
4                69              DELV        INTER              T
..              ...               ...          ...            ...
123              48              4DSD        HONDA              T
124              47               VAN        FRUEH              T
125              46               VAN        FRUEH              P
126              40              SUBN         FORD              T
127              16              2DSD        SMART              T

     Street Code1
0           161.0
1           161.0
2           161.0
3           161.0
4           151.0
..            ...
123        5952.0
124         181.0
125        2569.0
126        2969.0
127        4133.0

[128 rows x 10 columns]

In [20]:
grouped = csv.groupby('Registration State')
filtered_group = grouped.get_group('AZ')
print(filtered_group)

    Summons Number Plate ID Registration State Plate Type Issue Date
16      5093620865  AD80228                 AZ        PAS  9/24/2016  \

    Violation Code Vehicle Body Type Vehicle Make Issuing Agency  Street Code1
16               7                TK         FORD              V           NaN